# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    basedir: /app
  port: 8081
  servlet:
    context-path: /api
spring:
  # 环境 dev|test|prod
  profiles:
    active: dev
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
api:
  timeout: 15000
  switch:
    path:
      request: d://switch/request
      response: d://switch/response

